"use client";
import {useEffect,useRef,useState} from "react";

type Metrics={training?:{num_gaussians_final?:number;train_time_seconds?:number;extended?:{occlusion_confidence?:{frac_low_confidence?:number};phase2_accuracy_estimate_cm?:number}}};
export default function CesiumViewer({flightId="demo"}:{flightId?:string}){
 const ref=useRef<HTMLDivElement>(null),points=useRef<any[]>([]),line=useRef<any>(null),confidencePoints=useRef<any>(null); const [distance,setDistance]=useState<number|null>(null); const [confidence,setConfidence]=useState(false); const [metrics,setMetrics]=useState<Metrics>({});
 useEffect(()=>{let viewer:any,handler:any,stopped=false;(async()=>{try{const C=await import("@cesium/engine");if(stopped||!ref.current)return;const token=process.env.NEXT_PUBLIC_CESIUM_ION_TOKEN;if(token){C.Ion.defaultAccessToken=token}viewer=new C.CesiumWidget(ref.current,{scene3DOnly:true,shouldAnimate:false,baseLayer:false,globe:new C.Globe(C.Ellipsoid.WGS84),showRenderLoopErrors:false,contextOptions:{webgl:{failIfMajorPerformanceCaveat:false}}});
   viewer.scene.imageryLayers.addImageryProvider(new C.OpenStreetMapImageryProvider({url:"https://tile.openstreetmap.org/"}));
   if(token){try{viewer.scene.terrainProvider=await C.createWorldTerrainAsync()}catch(e){console.warn("Cesium Ion terrain unavailable; using ellipsoid terrain",e)}}
   line.current=new C.PolylineCollection();viewer.scene.primitives.add(line.current);confidencePoints.current=new C.PointPrimitiveCollection();viewer.scene.primitives.add(confidencePoints.current);
   handler=new C.ScreenSpaceEventHandler(viewer.scene.canvas);handler.setInputAction((m:any)=>{let p=viewer.scene.pickPosition?.(m.position);if(!p){const ray=viewer.camera.getPickRay(m.position);p=ray?viewer.scene.globe.pick(ray,viewer.scene):undefined}if(!p)p=viewer.camera.pickEllipsoid(m.position,C.Ellipsoid.WGS84);if(!p)return;points.current.push(p);if(points.current.length===2){const[a,b]=points.current;setDistance(C.Cartesian3.distance(a,b));line.current.removeAll();line.current.add({positions:[a,b],width:5,material:C.Material.fromType("Color",{color:C.Color.YELLOW})});points.current=[]}},C.ScreenSpaceEventType.LEFT_CLICK);
   const base=`/api/models/${flightId}`;const [meta,low,data]=await Promise.all([fetch(`${base}/geospatial_meta.json`).then(r=>r.json()),fetch(`${base}/low_confidence.json`).then(r=>r.ok?r.json():{points:[]}),fetch(`${base}/meta`).then(r=>r.ok?r.json():{})]);setMetrics(data);const o=meta.origin,matrix=C.Transforms.eastNorthUpToFixedFrame(C.Cartesian3.fromDegrees(o.lon,o.lat,o.alt));for(const xyz of low.points||[]){const p=C.Matrix4.multiplyByPoint(matrix,new C.Cartesian3(...xyz),new C.Cartesian3());confidencePoints.current.add({position:p,color:C.Color.RED,pixelSize:7,show:false})};const model=await C.Model.fromGltfAsync({url:`${base}/model.glb`,modelMatrix:matrix});viewer.scene.primitives.add(model);viewer.camera.flyTo({destination:C.Cartesian3.fromDegrees(o.lon,o.lat,o.alt+180),orientation:{heading:0,pitch:-C.Math.PI_OVER_TWO,roll:0}});
  }catch(e){console.warn("Cesium unavailable; viewer shell remains usable",e)}})();return()=>{stopped=true;handler?.destroy?.();viewer?.destroy?.()}},[flightId]);
 function toggleConfidence(){setConfidence(v=>{const next=!v;if(confidencePoints.current){for(let i=0;i<confidencePoints.current.length;i++)confidencePoints.current.get(i).show=next}return next})}
 const t=metrics.training;const ext=t?.extended;return <div className="viewer"><div ref={ref} className="globe"/><section className="hud"><div className="badge">{flightId==="demo"?"DEMO":"FLIGHT · "+flightId.slice(0,8)}</div><div>{flightId==="demo"?"Checked-in mock training frames":"Uploaded training flight"}</div><div>Click two model points to measure</div>{distance!==null&&<div>Distance: {distance.toFixed(2)} m</div>}<div>Gaussians: {(t?.num_gaussians_final||0).toLocaleString()} · Train: {t?.train_time_seconds??"—"} s</div><div>Accuracy: {ext?.phase2_accuracy_estimate_cm??"—"} cm</div><button onClick={toggleConfidence}>{confidence?"Hide":"Show"} low-confidence</button>{confidence&&<div style={{color:"#ff6868"}}>● {(((ext?.occlusion_confidence?.frac_low_confidence)||0)*100).toFixed(1)}% flagged occluded</div>}</section></div>
}
